spring.application.name=gestor-gastos

# Usa a vari�vel de ambiente DB_URL ou o valor padr�o (localhost)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestor_gastos}

# Usa a vari�vel DB_USERNAME ou 'postgres'
spring.datasource.username=${DB_USERNAME:postgres}

# Usa a vari�vel DB_PASSWORD ou sua senha local
spring.datasource.password=${DB_PASSWORD:34732044}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Em produ��o, update � o ideal. Evite create-drop para n�o perder dados.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true