spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_gastos
spring.datasource.username=postgres
spring.datasource.password=34732044
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update