spring.application.name=gestor-gastos

# Usa a variável de ambiente DB_URL ou o valor padrão (localhost)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestor_gastos}

# Usa a variável DB_USERNAME ou 'postgres'
spring.datasource.username=${DB_USERNAME:postgres}

# Usa a variável DB_PASSWORD ou sua senha local
spring.datasource.password=${DB_PASSWORD:34732044}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Em produção, update é o ideal. Evite create-drop para não perder dados.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true